import { strict as assert } from "node:assert/strict";
import { test } from "node:test";
import {
  ATHENA_GENERATED_FILE_PREFIX,
  defineAthenaConfig,
  GENERATED_FILE_BANNER,
  generateArtifactsFromSnapshot,
  isAthenaGeneratedSource,
  renderGeneratedFileHeader,
  renderObjectLiteral,
  renderObjectProperty,
  stripGeneratedFileHeader,
  withGeneratedFileBanner,
} from "../src/generator/index.ts";
import type { IntrospectionSnapshot } from "../src/schema/index.ts";

const LEGACY_BANNER = `/**
 * Generated by Athena.
 *
 * Do not edit manually.
 *
 * Source:
 * athena.config.ts
 */
`;

const snapshot: IntrospectionSnapshot = {
  backend: "postgresql",
  database: "neondb",
  generatedAt: "2026-08-18T21:10:37.285Z",
  schemas: {
    public: {
      name: "public",
      tables: {
        products: {
          columns: {
            id: {
              arrayDimensions: 0,
              dataType: "uuid",
              hasDefault: false,
              isGenerated: false,
              isNullable: false,
              isPrimaryKey: true,
              name: "id",
              typeKind: "scalar",
              udtName: "uuid",
            },
          },
          name: "products",
          primaryKey: ["id"],
          relations: {},
          schema: "public",
        },
      },
    },
  },
};

test("renderObjectProperty emits shorthand when key equals value identifier", () => {
  assert.equal(renderObjectProperty("accounts", "accounts"), "  accounts");
  assert.equal(
    renderObjectProperty("public", "publicSchema"),
    "  public: publicSchema"
  );
  assert.equal(
    renderObjectProperty("foo-bar", "fooBar"),
    "  'foo-bar': fooBar"
  );
  assert.equal(
    renderObjectLiteral([
      { key: "accounts", value: "accounts" },
      { key: "api_keys", value: "api_keys" },
      { key: "public", value: "publicSchema" },
    ]),
    ["  accounts,", "  api_keys,", "  public: publicSchema,"].join("\n")
  );
});

test("renderGeneratedFileHeader emits canonical @generated marker", () => {
  const header = renderGeneratedFileHeader({ source: "athena.config.ts" });
  assert.equal(header.startsWith(ATHENA_GENERATED_FILE_PREFIX), true);
  assert.equal(isAthenaGeneratedSource(header), true);
  assert.match(header, /@generated/);
  assert.match(header, /Generated by Athena\./);
  assert.match(header, /DO NOT EDIT MANUALLY\./);
  assert.match(header, /Changes will be overwritten by `athena-js generate`\./);
  assert.match(header, /Source: athena\.config\.ts/);
  assert.equal(header.includes("@autogenerated"), false);
  assert.equal(header.includes("@codegen"), false);
  assert.equal(GENERATED_FILE_BANNER, renderGeneratedFileHeader());
});

test("withGeneratedFileBanner is idempotent and never duplicates headers", () => {
  const body = `import { defineRegistry } from "@xylex-group/athena"\n`;
  const once = withGeneratedFileBanner(body);
  const twice = withGeneratedFileBanner(once);
  const thrice = withGeneratedFileBanner(withGeneratedFileBanner(twice));

  assert.equal(once, twice);
  assert.equal(twice, thrice);
  assert.equal(once.split("@generated").length - 1, 1);
  assert.equal(once.split("Generated by Athena").length - 1, 1);
  assert.equal(isAthenaGeneratedSource(once), true);
  assert.equal(once.startsWith(ATHENA_GENERATED_FILE_PREFIX), true);
  assert.match(once, /\*\/\n\nimport \{ defineRegistry \}/);
});

test("withGeneratedFileBanner replaces legacy banners instead of stacking", () => {
  const body = "export const registry = {}\n";
  const legacy = `${LEGACY_BANNER}\n${body}`;
  const stackedLegacy = `${LEGACY_BANNER}\n${LEGACY_BANNER}\n${body}`;

  const normalized = withGeneratedFileBanner(legacy);
  const normalizedStacked = withGeneratedFileBanner(stackedLegacy);

  assert.equal(normalized, normalizedStacked);
  assert.equal(normalized.split("Generated by Athena").length - 1, 1);
  assert.equal(normalized.includes("Do not edit manually."), false);
  assert.equal(normalized.includes("DO NOT EDIT MANUALLY."), true);
  assert.equal(normalized.includes("@generated"), true);
  assert.equal(stripGeneratedFileHeader(normalized), body);
});

test("isAthenaGeneratedSource recognizes legacy Athena banners", () => {
  assert.equal(isAthenaGeneratedSource(LEGACY_BANNER), true);
});

test("isAthenaGeneratedSource rejects generated-marker prose in custom files", () => {
  const customSources = [
    `/**
 * This file is not @generated; maintain it manually.
 */
export const custom = true;
`,
    `/**
 * Generated by Athena is a historical note, not an ownership marker.
 */
export const custom = true;
`,
    `/**
 * @generated
 * This file is intentionally maintained by hand.
 */
export const custom = true;
`,
  ];

  for (const source of customSources) {
    assert.equal(isAthenaGeneratedSource(source), false, source);
  }
});

test("generateArtifactsFromSnapshot emits a single @generated header per file", () => {
  const artifacts = generateArtifactsFromSnapshot(
    snapshot,
    defineAthenaConfig({
      output: {
        format: "table-builder",
        preset: "athena-direct",
      },
      provider: {
        connectionString: "postgres://127.0.0.1:5432/neondb",
        database: "neondb",
        kind: "postgres",
        mode: "direct",
        schemas: ["public"],
      },
    })
  );

  assert.ok(artifacts.files.length > 0);
  const kinds = new Set(artifacts.files.map((file) => file.kind));
  assert.equal(kinds.has("model"), true);
  assert.equal(kinds.has("schema"), true);
  assert.equal(kinds.has("database"), true);
  assert.equal(kinds.has("registry"), true);

  for (const file of artifacts.files) {
    assert.equal(
      isAthenaGeneratedSource(file.content),
      true,
      `${file.path} (${file.kind}) must start with ATHENA_GENERATED_FILE_PREFIX`
    );
    assert.equal(
      file.content.startsWith(ATHENA_GENERATED_FILE_PREFIX),
      true,
      `${file.path} must satisfy source.startsWith(ATHENA_GENERATED_FILE_PREFIX)`
    );
    assert.equal(
      file.content.split("@generated").length - 1,
      1,
      `${file.path} must contain exactly one @generated marker`
    );
    assert.equal(
      file.content.split("Generated by Athena").length - 1,
      1,
      `${file.path} must not duplicate the Athena banner`
    );
  }

  const model = artifacts.files.find((file) => file.kind === "model");
  assert.ok(model);
  assert.equal(isAthenaGeneratedSource(model.content), true);
  assert.match(model.content, /export const products = table\(/);

  const registry = artifacts.files.find((file) => file.kind === "registry");
  assert.ok(registry);
  assert.match(registry.content, /\* Source: athena\.config\.ts/);
  assert.doesNotMatch(registry.content, /\* Source:\s*\n/);
  assert.match(registry.content, /defineRegistry/);
  assert.match(registry.content, /__athena_schema_meta/);

  const database = artifacts.files.find((file) => file.kind === "database");
  assert.ok(database);
  assert.match(database.content, /\* Source: athena\.config\.ts/);
  assert.match(database.content, /^\s*public: publicSchema,$/m);
  assert.doesNotMatch(database.content, /['"]public['"]\s*:/);

  const schema = artifacts.files.find((file) => file.kind === "schema");
  assert.ok(schema);
  assert.match(schema.content, /\* @generated/);
  assert.match(schema.content, /^\s*products,$/m);
  assert.doesNotMatch(schema.content, /^\s*products:\s*products/m);
});

test("define-model artifacts also satisfy the @generated prefix invariant", () => {
  const artifacts = generateArtifactsFromSnapshot(
    snapshot,
    defineAthenaConfig({
      output: {
        format: "define-model",
        preset: "athena-direct",
      },
      provider: {
        connectionString: "postgres://127.0.0.1:5432/neondb",
        database: "neondb",
        kind: "postgres",
        mode: "direct",
        schemas: ["public"],
      },
    })
  );

  const model = artifacts.files.find((file) => file.kind === "model");
  assert.ok(model);
  assert.equal(isAthenaGeneratedSource(model.content), true);
  for (const file of artifacts.files) {
    assert.equal(isAthenaGeneratedSource(file.content), true);
  }
});
