import type { BillingProviderCapabilities } from "../types.ts";

export const MOLLIE_BILLING_PROVIDER_CAPABILITIES: BillingProviderCapabilities =
	{
		operations: {
			"customers.create": true,
			"customers.delete": true,
			"customers.get": true,
			"customers.list": true,
			"customers.update": true,
			"invoices.get": true,
			"invoices.list": true,
			"paymentLinks.create": true,
			"paymentLinks.delete": true,
			"paymentLinks.get": true,
			"paymentLinks.list": true,
			"paymentLinks.update": true,
			"payments.cancel": true,
			"payments.create": true,
			"payments.get": true,
			"payments.list": true,
			"refunds.cancel": true,
			"refunds.create": true,
			"refunds.get": true,
			"refunds.list": true,
			"subscriptions.cancel": true,
			"subscriptions.create": true,
			"subscriptions.get": true,
			"subscriptions.list": true,
			"subscriptions.update": true,
			"webhooks.create": false,
			"webhooks.delete": false,
			"webhooks.get": false,
			"webhooks.list": false,
			"webhooks.test": false,
			"webhooks.update": false,
		},
		ports: {
			customers: true,
			invoices: true,
			paymentLinks: true,
			payments: true,
			refunds: true,
			subscriptions: true,
			webhooks: false,
		},
	};
