/**
 * Local API key material helpers for the athena-js CLI.
 *
 * Generates cryptographically strong secrets for gateway `ATHENA_API_KEY`
 * / `.env.local` bootstrapping. This does **not** call Athena Auth
 * `POST /api-key/create` — use `client.auth.apiKey.create` for server-issued keys.
 */

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseEnvLine } from "./project-env.ts";

const DEFAULT_BYTES = 32;
const DEFAULT_PREFIX = "ath_";

function getRandomBytes(size: number): Uint8Array {
  return randomBytes(size);
}

function bytesToBase64Url(bytes: Uint8Array): string {
  return Buffer.from(bytes)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

export interface GenerateApiKeyOptions {
  /** Entropy bytes before encoding. Default 32. */
  bytes?: number;
  /** Prefix applied to the secret. Default `ath_`. Pass "" for none. */
  prefix?: string;
}

export interface GeneratedApiKey {
  /** Full secret including prefix. */
  key: string;
  prefix: string;
  /** Secret portion without prefix. */
  secret: string;
}

/**
 * Generate a local gateway-style API key secret.
 *
 * Format: `{prefix}{base64url(randomBytes)}` — suitable for `ATHENA_API_KEY`.
 */
export function generateApiKey(
  options: GenerateApiKeyOptions = {}
): GeneratedApiKey {
  const bytes = options.bytes ?? DEFAULT_BYTES;
  if (!Number.isInteger(bytes) || bytes < 16 || bytes > 64) {
    throw new Error("--bytes must be an integer between 16 and 64.");
  }

  const prefix =
    options.prefix === undefined ? DEFAULT_PREFIX : String(options.prefix);
  const secret = bytesToBase64Url(getRandomBytes(bytes));
  return {
    key: `${prefix}${secret}`,
    prefix,
    secret,
  };
}

export interface WriteApiKeyToEnvOptions {
  /** Absolute or cwd-relative env file path. Default `.env.local`. */
  filePath?: string;
  cwd?: string;
  /** Env key to set. Default `ATHENA_API_KEY`. */
  envKey?: string;
  /** Generated or provided key value. */
  key: string;
  /** Overwrite when the key already exists. Default false. */
  force?: boolean;
}

export interface WriteApiKeyToEnvResult {
  absolutePath: string;
  action: "created" | "updated" | "unchanged";
  envKey: string;
  previousPresent: boolean;
}

/**
 * Upsert an API key into a dotenv file without clobbering other keys.
 */
export function writeApiKeyToEnvFile(
  options: WriteApiKeyToEnvOptions
): WriteApiKeyToEnvResult {
  const cwd = options.cwd ?? process.cwd();
  const relative = options.filePath ?? ".env.local";
  const absolutePath = resolve(cwd, relative);
  const envKey = options.envKey ?? "ATHENA_API_KEY";
  const force = options.force === true;
  const lineValue = options.key.includes(" ")
    ? `"${options.key.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
    : options.key;
  const assignment = `${envKey}=${lineValue}`;

  if (!existsSync(absolutePath)) {
    const body = `# Generated by athena-js api-key generate\n${assignment}\n`;
    writeFileSync(absolutePath, body, "utf8");
    return {
      absolutePath,
      action: "created",
      envKey,
      previousPresent: false,
    };
  }

  const original = readFileSync(absolutePath, "utf8");
  const lines = original.split(/\r?\n/);
  let previousPresent = false;
  let replaced = false;
  let existingValue: string | undefined;
  const nextLines = lines.map((line) => {
    const parsed = parseEnvLine(line);
    if (!parsed || parsed[0] !== envKey) {
      return line;
    }
    previousPresent = true;
    existingValue = parsed[1];
    if (parsed[1] === options.key) {
      return line;
    }
    if (!force) {
      return line;
    }
    replaced = true;
    // Preserve export prefix if present.
    if (/^\s*export\s+/.test(line)) {
      return `export ${assignment}`;
    }
    return assignment;
  });

  if (previousPresent && !replaced) {
    if (existingValue === options.key) {
      return {
        absolutePath,
        action: "unchanged",
        envKey,
        previousPresent: true,
      };
    }
    throw new Error(
      `${envKey} already set in ${relative}. Re-run with --force to overwrite.`
    );
  }

  if (!previousPresent) {
    const needsNewline =
      original.length > 0 && !original.endsWith("\n") && !original.endsWith("\r");
    const suffix = `${needsNewline ? "\n" : ""}${assignment}\n`;
    writeFileSync(absolutePath, `${original}${suffix}`, "utf8");
    return {
      absolutePath,
      action: "updated",
      envKey,
      previousPresent: false,
    };
  }

  writeFileSync(absolutePath, `${nextLines.join("\n")}`, "utf8");
  return {
    absolutePath,
    action: "updated",
    envKey,
    previousPresent: true,
  };
}