-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.email_send_failures
    ADD COLUMN IF NOT EXISTS resolved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE athena.email_send_failures
    ADD COLUMN IF NOT EXISTS resolution_note TEXT;
ALTER TABLE athena.email_send_failures
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE INDEX IF NOT EXISTS idx_email_send_failures_resolved
    ON athena.email_send_failures (resolved);
CREATE INDEX IF NOT EXISTS idx_email_send_failures_flow
    ON athena.email_send_failures (flow);
ALTER TABLE athena.emails ADD COLUMN IF NOT EXISTS flow TEXT;
ALTER TABLE athena.emails ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE INDEX IF NOT EXISTS idx_emails_provider ON athena.emails (provider);
CREATE INDEX IF NOT EXISTS idx_emails_flow ON athena.emails (flow);
