-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.email_templates
    ADD COLUMN IF NOT EXISTS attachments JSONB NOT NULL DEFAULT '[]';
ALTER TABLE athena.email_templates
    ADD COLUMN IF NOT EXISTS attachment_failure_mode TEXT NOT NULL DEFAULT 'fail';
ALTER TABLE athena.email_templates
    ADD COLUMN IF NOT EXISTS variable_bindings JSONB NOT NULL DEFAULT '[]';
