-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.authorization_roles
    DROP CONSTRAINT IF EXISTS authorization_roles_scope_organization_id;
ALTER TABLE athena.authorization_roles
    ADD CONSTRAINT authorization_roles_scope_organization_id CHECK (
        (scope_kind = 'platform' AND organization_id IS NULL)
        OR (
            scope_kind = 'organization'
            AND (
                organization_id IS NULL
                OR (organization_id IS NOT NULL AND system_kind IS NULL)
            )
        )
    );
ALTER TABLE athena.authorization_revisions
    DROP CONSTRAINT IF EXISTS authorization_revisions_scope_nullability;
ALTER TABLE athena.authorization_revisions
    ADD CONSTRAINT authorization_revisions_scope_nullability CHECK (
        (scope_kind = 'platform' AND organization_id IS NULL)
        OR (scope_kind = 'organization' AND organization_id IS NOT NULL)
    );
CREATE OR REPLACE FUNCTION athena.authorization_assert_user_role_platform()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    role_scope TEXT;
    role_org TEXT;
BEGIN
    SELECT scope_kind, organization_id INTO role_scope, role_org
    FROM athena.authorization_roles
    WHERE id = NEW.role_id;
    IF role_scope IS DISTINCT FROM 'platform' OR role_org IS NOT NULL THEN
        RAISE EXCEPTION 'user assignments require a platform role';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS authorization_user_roles_platform ON athena.authorization_user_roles;
CREATE TRIGGER authorization_user_roles_platform
    BEFORE INSERT OR UPDATE ON athena.authorization_user_roles
    FOR EACH ROW
    EXECUTE PROCEDURE athena.authorization_assert_user_role_platform();
CREATE OR REPLACE FUNCTION athena.authorization_assert_member_role_organization()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    role_scope TEXT;
    role_org TEXT;
    member_org TEXT;
BEGIN
    SELECT scope_kind, organization_id INTO role_scope, role_org
    FROM athena.authorization_roles
    WHERE id = NEW.role_id;
    SELECT organization_id INTO member_org
    FROM athena.member
    WHERE id = NEW.member_id;
    IF role_scope IS DISTINCT FROM 'organization' THEN
        RAISE EXCEPTION 'member assignments require an organization role';
    END IF;
    IF role_org IS NOT NULL AND role_org IS DISTINCT FROM member_org THEN
        RAISE EXCEPTION 'custom role organization must match the member organization';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS authorization_member_roles_organization ON athena.authorization_member_roles;
CREATE TRIGGER authorization_member_roles_organization
    BEFORE INSERT OR UPDATE ON athena.authorization_member_roles
    FOR EACH ROW
    EXECUTE PROCEDURE athena.authorization_assert_member_role_organization();
