-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

CREATE TABLE IF NOT EXISTS athena.auth_signing_keys (
    kid TEXT PRIMARY KEY,
    issuer TEXT NOT NULL,
    status TEXT NOT NULL,
    algorithm TEXT NOT NULL DEFAULT 'ES256',
    public_jwk JSONB NOT NULL,
    private_jwk_ciphertext TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activated_at TIMESTAMPTZ,
    retires_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_signing_keys_active_issuer
    ON athena.auth_signing_keys (issuer)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_auth_signing_keys_issuer_status
    ON athena.auth_signing_keys (issuer, status);
