-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.email_send_failures
    ADD COLUMN IF NOT EXISTS error_code TEXT;
ALTER TABLE athena.email_send_failures
    ADD COLUMN IF NOT EXISTS template_id TEXT;
ALTER TABLE athena.email_send_failures
    ADD COLUMN IF NOT EXISTS template_key TEXT;
