-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.authorization_user_roles
    DROP CONSTRAINT IF EXISTS authorization_user_roles_pkey;
ALTER TABLE athena.authorization_user_roles
    ADD PRIMARY KEY (user_id, role_id);
CREATE INDEX IF NOT EXISTS idx_authorization_user_roles_user
    ON athena.authorization_user_roles (user_id);
ALTER TABLE athena.authorization_member_roles
    DROP CONSTRAINT IF EXISTS authorization_member_roles_pkey;
ALTER TABLE athena.authorization_member_roles
    ADD PRIMARY KEY (member_id, role_id);
CREATE INDEX IF NOT EXISTS idx_authorization_member_roles_member
    ON athena.authorization_member_roles (member_id);
