-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.api_keys
  ADD COLUMN IF NOT EXISTS scope_kind TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE athena.api_keys
  DROP CONSTRAINT IF EXISTS api_keys_organization_id_fkey;
ALTER TABLE athena.api_keys
  ADD CONSTRAINT api_keys_organization_id_fkey
  FOREIGN KEY (organization_id) REFERENCES athena.organization (id) ON DELETE CASCADE;
ALTER TABLE athena.api_keys
  DROP CONSTRAINT IF EXISTS api_keys_scope_kind_check;
ALTER TABLE athena.api_keys
  ADD CONSTRAINT api_keys_scope_kind_check
  CHECK (
    (scope_kind = 'organization' AND organization_id IS NOT NULL)
    OR
    (scope_kind IN ('legacy', 'platform') AND organization_id IS NULL)
  );
