-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

CREATE TABLE IF NOT EXISTS athena.oauth_clients (
    id TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_type TEXT NOT NULL DEFAULT 'public',
    registration_kind TEXT NOT NULL DEFAULT 'pre-registered',
    provider TEXT,
    response_type TEXT NOT NULL DEFAULT 'code',
    grant_type TEXT NOT NULL DEFAULT 'authorization_code',
    token_authentication_method TEXT NOT NULL DEFAULT 'none',
    redirect_uris TEXT[] NOT NULL,
    scopes TEXT[] NOT NULL DEFAULT '{}',
    resource_uris TEXT[] NOT NULL DEFAULT '{}',
    client_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT oauth_clients_type_check CHECK (client_type = 'public'),
    CONSTRAINT oauth_clients_response_type_check CHECK (response_type = 'code'),
    CONSTRAINT oauth_clients_grant_type_check CHECK (grant_type = 'authorization_code'),
    CONSTRAINT oauth_clients_token_auth_check CHECK (token_authentication_method = 'none')
);
CREATE INDEX IF NOT EXISTS idx_oauth_clients_active
  ON athena.oauth_clients (is_active);
