-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

CREATE TABLE IF NOT EXISTS athena.oauth_authorization_grants (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES athena.users (id) ON DELETE CASCADE,
    organization_id TEXT REFERENCES athena.organization (id) ON DELETE CASCADE,
    client_id TEXT NOT NULL REFERENCES athena.oauth_clients (id) ON DELETE CASCADE,
    resource TEXT NOT NULL,
    scopes TEXT[] NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'active',
    authorized_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by TEXT,
    revoke_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT oauth_grants_status_check
      CHECK (status IN ('active', 'expired', 'revoked')),
    CONSTRAINT oauth_grants_revoked_state_check
      CHECK ((status = 'revoked' AND revoked_at IS NOT NULL) OR status <> 'revoked')
);
CREATE INDEX IF NOT EXISTS idx_oauth_grants_user_id
  ON athena.oauth_authorization_grants (user_id);
CREATE INDEX IF NOT EXISTS idx_oauth_grants_client_id
  ON athena.oauth_authorization_grants (client_id);
CREATE INDEX IF NOT EXISTS idx_oauth_grants_organization_id
  ON athena.oauth_authorization_grants (organization_id);
CREATE INDEX IF NOT EXISTS idx_oauth_grants_status
  ON athena.oauth_authorization_grants (status);
CREATE INDEX IF NOT EXISTS idx_oauth_grants_expires_at
  ON athena.oauth_authorization_grants (expires_at);
DROP INDEX IF EXISTS athena.uq_oauth_grants_client_user_resource;
CREATE UNIQUE INDEX IF NOT EXISTS uq_oauth_grants_client_user_resource_org
  ON athena.oauth_authorization_grants (client_id, user_id, organization_id, resource)
  WHERE status = 'active' AND organization_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_oauth_grants_client_user_resource_platform
  ON athena.oauth_authorization_grants (client_id, user_id, resource)
  WHERE status = 'active' AND organization_id IS NULL;
