-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

CREATE TABLE IF NOT EXISTS athena.oauth_authorization_requests (
    id TEXT PRIMARY KEY,
    request_hash TEXT NOT NULL UNIQUE,
    client_id TEXT NOT NULL REFERENCES athena.oauth_clients (id) ON DELETE CASCADE,
    redirect_uri TEXT NOT NULL,
    resource TEXT NOT NULL,
    requested_scopes TEXT[] NOT NULL DEFAULT '{}',
    state_ciphertext TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    code_challenge_method TEXT NOT NULL DEFAULT 'S256',
    user_id TEXT REFERENCES athena.users (id) ON DELETE CASCADE,
    organization_id TEXT REFERENCES athena.organization (id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    CONSTRAINT oauth_requests_status_check
      CHECK (status IN ('pending', 'approved', 'denied', 'expired', 'consumed')),
    CONSTRAINT oauth_requests_pkce_check
      CHECK (code_challenge_method = 'S256')
);
CREATE INDEX IF NOT EXISTS idx_oauth_requests_expires_at
  ON athena.oauth_authorization_requests (expires_at);
CREATE INDEX IF NOT EXISTS idx_oauth_requests_user_id
  ON athena.oauth_authorization_requests (user_id);
