-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

CREATE TABLE IF NOT EXISTS athena.oauth_revoked_access_tokens (
    jti TEXT PRIMARY KEY,
    grant_id TEXT NOT NULL REFERENCES athena.oauth_authorization_grants (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reason TEXT
);
CREATE INDEX IF NOT EXISTS idx_oauth_revoked_access_tokens_expires_at
  ON athena.oauth_revoked_access_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_oauth_revoked_access_tokens_grant_id
  ON athena.oauth_revoked_access_tokens (grant_id);
