-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.sessions
  ADD COLUMN IF NOT EXISTS authenticated_at TIMESTAMPTZ;
UPDATE athena.sessions
  SET authenticated_at = created_at
  WHERE authenticated_at IS NULL;
ALTER TABLE athena.sessions
  ALTER COLUMN authenticated_at SET NOT NULL;
ALTER TABLE athena.sessions
  ADD COLUMN IF NOT EXISTS authentication_methods TEXT[] NOT NULL DEFAULT '{}';
