-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.oauth_authorization_grants
  ADD COLUMN IF NOT EXISTS identity_scopes TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE athena.oauth_authorization_requests
  ADD COLUMN IF NOT EXISTS identity_scopes TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS nonce TEXT,
  ADD COLUMN IF NOT EXISTS max_age INTEGER,
  ADD COLUMN IF NOT EXISTS prompt TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE athena.oauth_authorization_codes
  ADD COLUMN IF NOT EXISTS nonce TEXT,
  ADD COLUMN IF NOT EXISTS identity_scopes TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS authenticated_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS authentication_methods TEXT[] NOT NULL DEFAULT '{}';
UPDATE athena.oauth_authorization_codes
  SET authenticated_at = created_at
  WHERE authenticated_at IS NULL;
ALTER TABLE athena.oauth_authorization_codes
  ALTER COLUMN authenticated_at SET NOT NULL;
ALTER TABLE athena.oauth_authorization_requests
  ADD CONSTRAINT oauth_requests_max_age_check
    CHECK (max_age IS NULL OR max_age BETWEEN 0 AND 2147483647),
  ADD CONSTRAINT oauth_requests_prompt_check
    CHECK (prompt <@ ARRAY['none', 'login', 'consent']::TEXT[]
      AND NOT ('none' = ANY(prompt) AND cardinality(prompt) > 1));
ALTER TABLE athena.oauth_authorization_grants
  ADD CONSTRAINT oauth_grants_identity_scopes_check
    CHECK (identity_scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[]);
ALTER TABLE athena.oauth_authorization_codes
  ADD CONSTRAINT oauth_codes_identity_scopes_check
    CHECK (identity_scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[]);
ALTER TABLE athena.oauth_authorization_requests
  ADD CONSTRAINT oauth_requests_identity_scopes_check
    CHECK (identity_scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[]);
