-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

ALTER TABLE athena.oauth_refresh_tokens
  ADD COLUMN IF NOT EXISTS identity_scopes TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE athena.oauth_refresh_tokens
  ADD CONSTRAINT oauth_refresh_identity_scopes_check
    CHECK (identity_scopes <@ ARRAY['openid', 'profile', 'email']::TEXT[]);
DROP INDEX IF EXISTS athena.uq_auth_signing_keys_active_issuer;
CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_signing_keys_active_issuer
  ON athena.auth_signing_keys (issuer, algorithm)
  WHERE status = 'active';
