-- AUTO-GENERATED BY @xylex-group/athena
-- Embedded Athena Auth managed migration.
-- Do not edit. The package-owned migration definition is authoritative.

INSERT INTO athena.authorization_revisions (scope_kind, organization_id, revision)
SELECT 'organization', organization.id, 1
FROM athena.organization AS organization
ON CONFLICT (organization_id) WHERE organization_id IS NOT NULL DO NOTHING;
