/**
 * athena-js
 *
 * database driver API gateway SDK — Athena client for the Athena HTTP API
 * built by XYLEX Group
 */

// Athena client
export { createClient, AthenaClient } from "./client.js";
export { Backend } from "./gateway/types.js";
export { AthenaGatewayError, isAthenaGatewayError } from "./gateway/errors.ts";
export { verifyAthenaGatewayUrl } from "./gateway/client.ts";
export { normalizeAthenaGatewayBaseUrl } from "./gateway/url.ts";
export {
  isOk,
  unwrap,
  unwrapRows,
  unwrapOne,
  requireSuccess,
  requireAffected,
  parseBooleanFlag,
  normalizeAthenaError,
  coerceInt,
  assertInt,
  withRetry,
  AthenaError,
  AthenaErrorCode,
  AthenaErrorKind,
  AthenaErrorCategory,
} from './auxiliaries.js'
export { identifier } from './sql-identifiers.ts'
export type {
  AthenaFindManyOptions,
  AthenaFindManyResult,
  AthenaOrderBy,
  AthenaRelationSelectNode,
  AthenaSelectShape,
  AthenaWhere,
  AthenaWhereBooleanOperand,
  AthenaWhereOperatorInput,
} from './query-ast.ts'
export {
  createTypedClient,
  defineDatabase,
  defineModel,
  defineRegistry,
  defineSchema,
  createModelFormAdapter,
  toModelFormDefaults,
  toModelPayload,
  createPostgresIntrospectionProvider,
} from './schema/index.ts'
export {
  defineGeneratorConfig,
  findGeneratorConfigPath,
  generatorEnv,
  loadGeneratorConfig,
  normalizeGeneratorConfig,
  DEFAULT_POSTGRES_SCHEMAS,
  generateArtifactsFromSnapshot,
  normalizeSchemaSelection,
  resolvePostgresColumnType,
  resolveGeneratorProvider,
  resolveProviderSchemas,
  runSchemaGenerator,
} from './generator/index.ts'
export {
  createAuthClient,
  ATHENA_AUTH_BASE_ERROR_CODES,
  athenaAuth,
  defineAthenaAuthConfig,
  drizzleAdapter,
  tanstackStartCookies,
  renderAthenaReactEmail,
  createAuthReactEmailInput,
  defineAuthEmailTemplate,
} from './auth/index.ts'
export { storageSdkManifest, AthenaStorageError } from './storage/module.ts'
export type {
  AthenaClientExperimentalOptions,
  AthenaQueryTraceOptions,
  AthenaQueryTraceCallsite,
  AthenaQueryTraceEvent,
  AthenaFromOptions,
  RpcQueryBuilder,
  RpcOrderOptions,
  AthenaCreateClientOptions,
  AthenaCreateClientOptionsWithStorage,
  AthenaSdkClient,
  AthenaSdkClientWithAuth,
  AthenaSdkClientWithStorage,
  TableQueryBuilder,
  AthenaResult,
  AthenaResultError,
} from "./client.js";
export type { AthenaDbModule } from './db/module.js'
export type {
  AthenaEnvelope,
  AthenaStorageCallOptions,
  AthenaStorageErrorCode,
  AthenaStorageModule,
  CreateStorageCatalogRequest,
  CreateStorageUploadUrlRequest,
  CreateStorageUploadUrlsRequest,
  DeleteStorageFolderRequest,
  GetStorageFileUrlQuery,
  ListStorageFilesRequest,
  ManagedFileRecord,
  MoveStorageFolderRequest,
  PresignedFileUrlResponse,
  S3CatalogItem,
  S3CredentialListItem,
  SetStorageFileVisibilityRequest,
  StorageBatchUploadUrlResponse,
  StorageFileMutationResponse,
  StorageFolderMutationResponse,
  StorageListFilesResponse,
  StorageUploadUrlResponse,
  UpdateStorageCatalogRequest,
  UpdateStorageFileRequest,
} from './storage/module.js'
export type {
  AthenaErrorInput,
  AthenaOperationContext,
  NormalizedAthenaError,
  UnwrapOptions,
  UnwrapOneOptions,
  RequireAffectedOptions,
  IntCoercionOptions,
  RetryConfig,
  RetryBackoffStrategy,
} from './auxiliaries.js'
export type {
  DatabaseDef,
  InsertOf,
  IntrospectionColumn,
  IntrospectionInspectOptions,
  IntrospectionRelation,
  IntrospectionSchema,
  IntrospectionSnapshot,
  IntrospectionTable,
  IntrospectionTypeKind,
  ModelAt,
  ModelDef,
  ModelMetadata,
  ModelRelationKind,
  ModelRelationMetadata,
  PostgresIntrospectionProviderOptions,
  RegistryDef,
  RowOf,
  SchemaDef,
  SchemaIntrospectionProvider,
  ModelFormAdapter,
  ModelFormDefaults,
  ModelFormNullishMode,
  ModelFormValues,
  TenantContext,
  TenantContextValue,
  TenantKeyMap,
  ToModelFormDefaultsOptions,
  ToModelPayloadOptions,
  TypedAthenaClient,
  TypedClientOptions,
  UpdateOf,
} from './schema/index.ts'
export type {
  AthenaGeneratorConfig,
  GeneratedArtifact,
  GeneratedArtifacts,
  GeneratorEnvBooleanOptions,
  GeneratorEnvJsonOptions,
  GeneratorEnvListOptions,
  GeneratorEnvOneOfOptions,
  GeneratorEnvStringOptions,
  GeneratorArtifactKind,
  GeneratorExperimentalFlags,
  GeneratorFeatureFlags,
  GeneratorNamingConfig,
  GeneratorOutputConfig,
  GeneratorOutputTargets,
  GeneratorProviderConfig,
  GeneratorSchemaSelection,
  LoadGeneratorConfigOptions,
  LoadedGeneratorConfig,
  NamingStyle,
  NormalizedAthenaGeneratorConfig,
  RunGeneratorOptions,
  RunGeneratorResult,
} from './generator/index.ts'
export type {
  AthenaAuthQueryPrimitive,
  AthenaAuthQueryValue,
  AthenaAuthCredentials,
  AthenaAuthCallOptions,
  AthenaAuthBaseURLConfig,
  AthenaAuthClientConfig,
  AthenaAuthEndpointPath,
  AthenaAuthErrorCode,
  AthenaAuthErrorDetails,
  AthenaAuthRequestInput,
  AthenaAuthMethod,
  AthenaAuthResult,
  AthenaAuthBindings,
  AthenaAuthStatusResponse,
  AthenaAuthRevokeSessionRequest,
  AthenaAuthSessionRevokeBinding,
  AthenaAuthAdminUserSessionRevokeBinding,
  AthenaAuthResetPasswordBinding,
  AthenaAuthGenericInput,
  AthenaAuthGenericQueryInput,
  AthenaAuthSdkClient,
  AthenaAuthSocialRedirectResponse,
  AthenaAuthEmailChangeResponse,
  AthenaAuthLinkedAccount,
  AthenaAuthOrganization,
  AthenaAuthOrganizationMember,
  AthenaAuthOrganizationInvitation,
  AthenaAuthOrganizationBindings,
  AthenaOAuthTokenBundle,
  AthenaOAuthAccountTokenRequest,
  AthenaForgetPasswordRequest,
  AthenaResetPasswordRequest,
  AthenaVerifyEmailRequest,
  AthenaSendVerificationEmailRequest,
  AthenaChangeEmailRequest,
  AthenaChangePasswordRequest,
  AthenaUpdateUserRequest,
  AthenaDeleteUserRequest,
  AthenaDeleteUserCallbackRequest,
  AthenaDeleteUserResponse,
  AthenaAuthReactEmailProps,
  AthenaAuthReactEmailComponent,
  AthenaAuthReactEmailRenderInput,
  AthenaAuthReactEmailRenderOptions,
  AthenaAuthReactEmailConfig,
  AthenaAuthReactEmailEventPhase,
  AthenaAuthReactEmailRenderEvent,
  AthenaAuthEmailTemplateDefinition,
  AthenaAuthEmailTemplateReactOverrides,
  AthenaAuthEmailTemplateCreateFromDefinitionInput,
  AthenaAuthEmailTemplateUpdateFromDefinitionInput,
  AthenaAuthEmailTemplateBuilder,
  AthenaLinkSocialRequest,
  AthenaUnlinkAccountRequest,
  AthenaAuthSession,
  AthenaAuthSessionResponse,
  AthenaSocialSignInRequest,
  AthenaUsernameSignInRequest,
  AthenaAuthSignInResponse,
  AthenaAuthSignOutResponse,
  AthenaAuthUser,
  AthenaEmailSignInRequest,
  AthenaEmailSignUpRequest,
  AthenaAuthSearchOperator,
  AthenaAuthFilterOperator,
  AthenaAdminListUsersSearchOperator,
  AthenaAdminListUsersFilterOperator,
  AthenaAdminListUsersQuery,
  AthenaAuthContext,
  AthenaAuthCookieRuntimeInput,
  AthenaAuthDatabaseAdapter,
  AthenaAuthDatabaseFactory,
  AthenaAuthHandlerResult,
  AthenaAuthPlugin,
  AthenaAuthPluginContext,
  AthenaAuthPluginHandlerContext,
  AthenaAuthRequestContext,
  AthenaAuthServer,
  AthenaAuthServerApi,
  AthenaAuthServerConfig,
  AthenaAuthServerRuntimeOptions,
  AthenaAuthSocialProviderConfig,
  AthenaAuthTrustedOrigins,
  AthenaAuthTrustedProviders,
  AthenaDrizzleAdapterOptions,
} from './auth/index.ts'
export type {
  AthenaJsonPrimitive,
  AthenaJsonValue,
  AthenaJsonObject,
  AthenaJsonArray,
  AthenaConditionCastType,
  AthenaRpcCallOptions,
  AthenaRpcFilter,
  AthenaRpcFilterOperator,
  AthenaRpcOrder,
  AthenaRpcPayload,
  AthenaGatewayErrorCode,
  AthenaGatewayErrorDetails,
  AthenaGatewayConnectionOptions,
  AthenaGatewayConnectionResult,
  BackendType,
  BackendConfig,
  AthenaGatewayCallOptions,
} from "./gateway/types.js";
