/**
 * athena-js
 *
 * database driver API gateway SDK — Athena client for the Athena HTTP API
 * built by XYLEX Group
 */

// Athena client
export { createClient, AthenaClient } from "./client.js";
export { Backend } from "./gateway/types.js";
export { AthenaGatewayError, isAthenaGatewayError } from "./gateway/errors.ts";
export {
  isOk,
  unwrap,
  unwrapRows,
  unwrapOne,
  requireSuccess,
  requireAffected,
  parseBooleanFlag,
  normalizeAthenaError,
  coerceInt,
  assertInt,
  withRetry,
  AthenaError,
  AthenaErrorCode,
  AthenaErrorKind,
  AthenaErrorCategory,
} from './auxiliaries.js'
export { identifier } from './sql-identifiers.ts'
export {
  createTypedClient,
  defineDatabase,
  defineModel,
  defineRegistry,
  defineSchema,
  createModelFormAdapter,
  toModelFormDefaults,
  toModelPayload,
  createPostgresIntrospectionProvider,
} from './schema/index.ts'
export {
  defineGeneratorConfig,
  findGeneratorConfigPath,
  loadGeneratorConfig,
  normalizeGeneratorConfig,
  DEFAULT_POSTGRES_SCHEMAS,
  generateArtifactsFromSnapshot,
  normalizeSchemaSelection,
  resolvePostgresColumnType,
  resolveGeneratorProvider,
  resolveProviderSchemas,
  runSchemaGenerator,
} from './generator/index.ts'
export { createAuthClient } from './auth/index.ts'
export type {
  AthenaClientExperimentalOptions,
  RpcQueryBuilder,
  RpcOrderOptions,
  AthenaCreateClientOptions,
  AthenaSdkClient,
  AthenaSdkClientWithAuth,
  TableQueryBuilder,
  AthenaResult,
} from "./client.js";
export type {
  AthenaErrorInput,
  AthenaOperationContext,
  NormalizedAthenaError,
  UnwrapOptions,
  UnwrapOneOptions,
  RequireAffectedOptions,
  IntCoercionOptions,
  RetryConfig,
  RetryBackoffStrategy,
} from './auxiliaries.js'
export type {
  DatabaseDef,
  InsertOf,
  IntrospectionColumn,
  IntrospectionInspectOptions,
  IntrospectionRelation,
  IntrospectionSchema,
  IntrospectionSnapshot,
  IntrospectionTable,
  IntrospectionTypeKind,
  ModelAt,
  ModelDef,
  ModelMetadata,
  ModelRelationKind,
  ModelRelationMetadata,
  PostgresIntrospectionProviderOptions,
  RegistryDef,
  RowOf,
  SchemaDef,
  SchemaIntrospectionProvider,
  ModelFormAdapter,
  ModelFormDefaults,
  ModelFormNullishMode,
  ModelFormValues,
  TenantContext,
  TenantContextValue,
  TenantKeyMap,
  ToModelFormDefaultsOptions,
  ToModelPayloadOptions,
  TypedAthenaClient,
  TypedClientOptions,
  UpdateOf,
} from './schema/index.ts'
export type {
  AthenaGeneratorConfig,
  GeneratedArtifact,
  GeneratedArtifacts,
  GeneratorArtifactKind,
  GeneratorExperimentalFlags,
  GeneratorFeatureFlags,
  GeneratorNamingConfig,
  GeneratorOutputConfig,
  GeneratorOutputTargets,
  GeneratorProviderConfig,
  GeneratorSchemaSelection,
  LoadGeneratorConfigOptions,
  LoadedGeneratorConfig,
  NamingStyle,
  NormalizedAthenaGeneratorConfig,
  RunGeneratorOptions,
  RunGeneratorResult,
} from './generator/index.ts'
export type {
  AthenaAuthQueryPrimitive,
  AthenaAuthQueryValue,
  AthenaAuthCredentials,
  AthenaAuthCallOptions,
  AthenaAuthClientConfig,
  AthenaAuthEndpointPath,
  AthenaAuthErrorCode,
  AthenaAuthErrorDetails,
  AthenaAuthRequestInput,
  AthenaAuthMethod,
  AthenaAuthResult,
  AthenaAuthBindings,
  AthenaAuthStatusResponse,
  AthenaAuthRevokeSessionRequest,
  AthenaAuthSessionRevokeBinding,
  AthenaAuthAdminUserSessionRevokeBinding,
  AthenaAuthResetPasswordBinding,
  AthenaAuthGenericInput,
  AthenaAuthGenericQueryInput,
  AthenaAuthSdkClient,
  AthenaAuthSocialRedirectResponse,
  AthenaAuthEmailChangeResponse,
  AthenaAuthLinkedAccount,
  AthenaAuthOrganization,
  AthenaAuthOrganizationMember,
  AthenaAuthOrganizationInvitation,
  AthenaAuthOrganizationBindings,
  AthenaOAuthTokenBundle,
  AthenaOAuthAccountTokenRequest,
  AthenaForgetPasswordRequest,
  AthenaResetPasswordRequest,
  AthenaVerifyEmailRequest,
  AthenaSendVerificationEmailRequest,
  AthenaChangeEmailRequest,
  AthenaChangePasswordRequest,
  AthenaUpdateUserRequest,
  AthenaDeleteUserRequest,
  AthenaDeleteUserCallbackRequest,
  AthenaDeleteUserResponse,
  AthenaLinkSocialRequest,
  AthenaUnlinkAccountRequest,
  AthenaAuthSession,
  AthenaAuthSessionResponse,
  AthenaSocialSignInRequest,
  AthenaUsernameSignInRequest,
  AthenaAuthSignInResponse,
  AthenaAuthSignOutResponse,
  AthenaAuthUser,
  AthenaEmailSignInRequest,
  AthenaEmailSignUpRequest,
} from './auth/index.ts'
export type {
  AthenaJsonPrimitive,
  AthenaJsonValue,
  AthenaJsonObject,
  AthenaJsonArray,
  AthenaConditionCastType,
  AthenaRpcCallOptions,
  AthenaRpcFilter,
  AthenaRpcFilterOperator,
  AthenaRpcOrder,
  AthenaRpcPayload,
  AthenaGatewayErrorCode,
  AthenaGatewayErrorDetails,
  BackendType,
  BackendConfig,
  AthenaGatewayCallOptions,
} from "./gateway/types.js";
